"""empty message

Revision ID: 46e1202ca246
Revises: 
Create Date: 2023-03-12 21:58:18.560922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e1202ca246'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('propertyTitle', sa.String(length=120), nullable=False),
    sa.Column('propertyDescription', sa.String(length=120), nullable=False),
    sa.Column('numofrooms', sa.Integer(), nullable=False),
    sa.Column('numofbathrooms', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(length=120), nullable=False),
    sa.Column('propertytype', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('photo_path', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_profile')
    # ### end Alembic commands ###
